[build]
  command = "astro build"
  functions = "netlify/functions"
  publish = "dist"

[[plugins]] 
  package = "netlify-plugin-cypress"
  inputs = { enable = false }

  [plugins.inputs.postBuild]
    enable = true
  
  [plugins.inputs]
    enable = false
